spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/medicine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      mode: always
#      data-locations: classpath*:initialization/schema.sql
#      platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath*:liquibase/changelog.yml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false