app:
  dbone:
    datasource:
    url: jdbc:postgresql://localhost:5432/medicine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  dbtwo:
    datasource:
      url: jdbc:postgresql://localhost:5432/db_log
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
spring:
  sql:
    init:
      mode: always
      data-locations: classpath*:initialization/data.sql
      platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    open-in-view: false
  thymeleaf:
    cache: false
server:
  port: 8081
logging:
  file:
    name: person-logs.log
    path: classpath*:logs/person-logs.log
datasource:
  secondary:
    liquibase:
      liquibase/db.changelog-master.yaml
