spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/medicine
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: classpath*:initialization/schema.sql
      platform: org.hibernate.dialect.PostgreSQLDialect